apiVersion: v1
kind: Service
metadata:
  name: svc-postgres
  labels:
    app: svc-postgres
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
      name: postgres
  selector:
    app: pg-deployment
