apiVersion: v1
kind: Service
metadata:
  name: svc-rmq-queue
  labels:
    app: svc-rmq-queue
spec:
  selector:
    app: rmq-deployment
  ports:
    - protocol: TCP
      port: 5672
      targetPort: 5672
      name: rabbitmq
    - protocol: TCP
      port: 15672
      targetPort: 15672
      name: rabbitmq-management
  type: LoadBalancer
