apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-production-pvc
spec:
  storageClassName: mongo-production-standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-production-storage
spec:
  storageClassName: mongo-production-standard
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/mongo"
    type: DirectoryOrCreate
