apiVersion: v1
kind: Service
metadata:
  name: svc-mongodb-production
  labels:
    app: svc-mongodb-production
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 27018
      targetPort: 27018
      name: mongodb-production
  selector:
    app: mongo-production-deployment
