apiVersion: v1
kind: ConfigMap
metadata:
  name: mongo-production-configmap
data:
  MONGO_INITDB_ROOT_USERNAME: root
  MONGO_INITDB_ROOT_PASSWORD: root
  MONGO_INITDB_DATABASE: production-manager
  MONGO_REPLICA_HOST: localhost
  MONGO_REPLICA_PORT: "27018"
  MONGO_COMMAND: mongo
