apiVersion: v1
kind: Service
metadata:
  name: svc-ms-ordermanager
  labels:
    app: svc-ms-ordermanager
spec:
  selector:
    app: ms-ordermanager-deployment
  type: LoadBalancer
  ports:
    - port: 5000
      protocol: TCP
      targetPort: 5000
