apiVersion: apps/v1
kind: Deployment
metadata:
  name: rmq-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rmq-deployment
  template:
    metadata:
      labels:
        app: rmq-deployment
    spec:
      containers:
        - name: rmq-deployment
          image: rabbitmq:3.8-management
          ports:
            - containerPort: 5672
            - containerPort: 15672
          volumeMounts:
            - mountPath: /data/rmqdata
              name: rmq-queue
          envFrom:
            - configMapRef:
                name: rmq-configmap
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
      volumes:
        - name: rmq-queue
          persistentVolumeClaim:
            claimName: rmq-pvc
