apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rmq-pvc
spec:
  storageClassName: rmq-standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: rmq-storage
spec:
  storageClassName: rmq-standard
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/rabbitmq"
    type: DirectoryOrCreate
